name: 'Fraim Security'
description: 'Run Fraim AI-powered workflows on your code and upload results to GitHub Security tab'
author: 'Fraim Team'

branding:
  icon: 'shield'
  color: 'blue'

inputs:
  workflows:
    description: 'Workflows to run (comma-separated). Available: code, iac'
    required: false
    default: 'code'
  
  gemini-api-key:
    description: 'Google Gemini API key for AI analysis'
    required: false

  openai-api-key:
    description: 'OpenAI API key for AI analysis (alternative to Gemini)'
    required: false

  model:
    description: 'AI model to use for analysis'
    required: false
    default: 'gemini/gemini-2.5-flash'
    choices:
      # Gemini Models
      - 'gemini/gemini-2.5-flash'
      - 'gemini/gemini-2.5-flash-lite-preview-06-17'
      - 'gemini/gemini-2.5-pro'
      # OpenAI Models  
      - 'openai/gpt-4.1'
      - 'openai/gpt-4.1-mini'
      - 'openai/gpt-4.1-nano'
      - 'openai/gpt-4o'
      - 'openai/gpt-4o-mini'
      - 'openai/gpt-4-turbo'

  confidence:
    description: 'Minimum confidence threshold (1-10) for filtering findings'
    required: false
    default: '8'

outputs:
  sarif-file:
    description: 'Path to the generated SARIF file'
    value: ${{ steps.fraim-scan.outputs.sarif-file }}
  
  results-count:
    description: 'Number of security findings'
    value: ${{ steps.fraim-scan.outputs.results-count }}

permissions:
  contents: read
  actions: read
  security-events: write
  pull-requests: write

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch full history for proper diff analysis

    - name: Install uv
      uses: astral-sh/setup-uv@bd01e18f51369d5a26f1651c3cb451d3417e3bba
      with:
        version: "0.7.14"
        enable-cache: false

    - name: Get Fraim v0.2.1
      shell: bash
      run: |
        uv tool install fraim==v0.2.1

    - name: Run Fraim Security Scan
      id: fraim-scan
      shell: bash
      run: |
        chmod +x ${{ github.action_path }}/fraim-scan.sh
        ${{ github.action_path }}/fraim-scan.sh
      env:
        GEMINI_API_KEY: ${{ inputs.gemini-api-key }}
        OPENAI_API_KEY: ${{ inputs.openai-api-key }}
        INPUT_MODEL: ${{ inputs.model }}
        INPUT_WORKFLOWS: ${{ inputs.workflows }}
        GITHUB_EVENT_NAME: ${{ github.event_name }}
        GITHUB_BASE_SHA: ${{ github.event.pull_request.base.sha }}
        GITHUB_SHA: ${{ github.sha }}

    - name: Upload SARIF to GitHub Security
      if: steps.fraim-scan.outputs.sarif-file != ''
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: ${{ steps.fraim-scan.outputs.sarif-file }}
        category: fraim-security-scan
        # Ensure proper PR annotations by specifying the commit SHA
        checkout_path: ${{ github.workspace }}
        ref: ${{ github.ref }}
        sha: ${{ github.sha }}

    - name: Upload SARIF as artifact
      if: steps.fraim-scan.outputs.sarif-file != ''
      uses: actions/upload-artifact@v4
      with:
        name: fraim-sarif-results
        path: ${{ steps.fraim-scan.outputs.sarif-file }}
        retention-days: 30
