# Example GitHub Actions workflow for Fraim Security Scan
# Copy this file to .github/workflows/security.yml in your repository

name: Security Scan with Fraim

on:
  pull_request:
    branches: [main, master]
  pull_request_review:
    branches: [main, master]
  push:
    branches: [main, master]
  schedule:
    # Run weekly full scan on Sundays at 2 AM UTC
    - cron: '0 2 * * 0'

jobs:
  security-scan:
    name: Fraim Security Analysis
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      actions: read
      security-events: write
      pull-requests: write
    
    steps:
      - name: Run Fraim Security Scan
        id: fraim-scan
        uses: fraim-dev/fraim-action@v0  # Use v0 for latest v0.x.x releases
        with:
          # Required: Set up your API key in repository secrets (choose one)
          gemini-api-key: ${{ secrets.GEMINI_API_KEY }}
          # openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          
          # AI model to use (default: anthropic/claude-sonnet-4-20250514)
          model: 'gemini/gemini-2.5-flash'
          # Alternative models:
          # model: 'openai/gpt-4o-mini'
          # model: 'anthropic/claude-sonnet-4-20250514'

          # Required: Workflow to run (code, iac, or risk_flagger)
          workflow: 'risk_flagger'
          
          # Required: Workflow-specific arguments as JSON object
          workflow_args: |
            {
              "confidence": "8",
              "custom_risk_list_json": "",
              "custom_risk_list_filepath": "",
              "custom_risk_list_action": "merge",
              "approver": "security-team-lead",
              "should_block_pull_request": "true"
            }